camel:
  springboot:
    name: SupplierManager
  component:
    servlet:
      mapping:
        enabled: true
        context-path: /restock/*

quickstart:
  generateOrderPeriod: 1s
  processOrderPeriod: 3s
